
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicComboBoxRenderer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gulbe
 */
public class AddPersonnel extends javax.swing.JFrame {
    private Personnel currentPersonnel;
    private DefaultTableModel Model;
    
    /**
     * Creates new form AddPersonnel
     */
    public AddPersonnel() {
        initComponents();
    }
    
    public AddPersonnel(DefaultTableModel Model) {
        this.Model = Model;
        initComponents();
    }
    
private void createPersonnel(){
       String Name = TxtFieldN.getText();
       String Surname = TxtFieldSN.getText();
       String RegisterNumber = TxtFieldRN.getText();
       String Position = ComboBoxPos.getSelectedItem().toString();
       String YearOfStart = TxtFieldYOS.getText();
       boolean NameCheck = Name.isEmpty();
       boolean SurnameCheck = Surname.isEmpty();
       boolean RegisterNumberCheck = RegisterNumber.isEmpty();
       boolean YearOfStartCheck = YearOfStart.isEmpty();
        if (NameCheck) {
            JOptionPane.showMessageDialog(this, "Name Field is empty!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (SurnameCheck) {
            JOptionPane.showMessageDialog(this, "Lastname Field is empty!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (RegisterNumberCheck) {
            JOptionPane.showMessageDialog(this, "Register Number Field is empty!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (YearOfStartCheck) {
            JOptionPane.showMessageDialog(this, "Year of Start Field is empty!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        if (!NameCheck && !SurnameCheck && !RegisterNumberCheck && !YearOfStartCheck) {
            currentPersonnel= new Personnel (Name , Surname , RegisterNumber,Position, YearOfStart);
            JOptionPane.showMessageDialog(this, "Personnel is created Successfully!", "Sucess!", JOptionPane.INFORMATION_MESSAGE);

        }
      // for (int i = 0; i < Personnel.personnelList.size(); i++){
          // Personnel.get(i).setPosition=ComboBoxPos.getSelectedIndex();
           //;
      // }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        PanelAddPersonnel = new javax.swing.JPanel();
        jLabelPersonnel = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelSurName = new javax.swing.JLabel();
        jLabelRegNO = new javax.swing.JLabel();
        jLabelPosition = new javax.swing.JLabel();
        jLabelYearOfStart = new javax.swing.JLabel();
        TxtFieldN = new javax.swing.JTextField();
        TxtFieldSN = new javax.swing.JTextField();
        TxtFieldRN = new javax.swing.JTextField();
        TxtFieldYOS = new javax.swing.JTextField();
        jButtonADD = new javax.swing.JButton();
        jButtonCLEAR = new javax.swing.JButton();
        ComboBoxPos = new javax.swing.JComboBox<>();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Personnel");

        PanelAddPersonnel.setBackground(new java.awt.Color(255, 232, 245));

        jLabelPersonnel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelPersonnel.setText("PERSONNEL");

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelName.setText("Name");

        jLabelSurName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelSurName.setText("Surname");

        jLabelRegNO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelRegNO.setText("Register Number");

        jLabelPosition.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelPosition.setText("Position");

        jLabelYearOfStart.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelYearOfStart.setText("Year Of Start");

        TxtFieldN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldNActionPerformed(evt);
            }
        });

        TxtFieldSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldSNActionPerformed(evt);
            }
        });

        TxtFieldYOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldYOSActionPerformed(evt);
            }
        });

        jButtonADD.setText("ADD");
        jButtonADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDActionPerformed(evt);
            }
        });

        jButtonCLEAR.setText("CLEAR");
        jButtonCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLEARActionPerformed(evt);
            }
        });

        ComboBoxPos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FacultyMembers", "ReserachAssistant", "Officers", "PartTimeEmployee", "Worker", "Chief", "Security" }));
        ComboBoxPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxPosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAddPersonnelLayout = new javax.swing.GroupLayout(PanelAddPersonnel);
        PanelAddPersonnel.setLayout(PanelAddPersonnelLayout);
        PanelAddPersonnelLayout.setHorizontalGroup(
            PanelAddPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAddPersonnelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelAddPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAddPersonnelLayout.createSequentialGroup()
                        .addComponent(jLabelPersonnel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelAddPersonnelLayout.createSequentialGroup()
                        .addGroup(PanelAddPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRegNO)
                            .addComponent(jLabelPosition)
                            .addComponent(jLabelYearOfStart)
                            .addComponent(jLabelSurName)
                            .addComponent(jLabelName))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAddPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ComboBoxPos, 0, 319, Short.MAX_VALUE)
                            .addComponent(TxtFieldRN)
                            .addComponent(TxtFieldSN)
                            .addComponent(TxtFieldN)
                            .addComponent(TxtFieldYOS))
                        .addContainerGap(26, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAddPersonnelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonADD, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButtonCLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        PanelAddPersonnelLayout.setVerticalGroup(
            PanelAddPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAddPersonnelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelAddPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelAddPersonnelLayout.createSequentialGroup()
                        .addGroup(PanelAddPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAddPersonnelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabelName))
                            .addGroup(PanelAddPersonnelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TxtFieldN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelAddPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAddPersonnelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabelSurName))
                            .addGroup(PanelAddPersonnelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(TxtFieldSN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAddPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAddPersonnelLayout.createSequentialGroup()
                                .addGroup(PanelAddPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelRegNO)
                                    .addComponent(TxtFieldRN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(jLabelPosition))
                            .addComponent(ComboBoxPos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabelYearOfStart))
                    .addGroup(PanelAddPersonnelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TxtFieldYOS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(32, 32, 32)
                .addGroup(PanelAddPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonADD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAddPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAddPersonnel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFieldYOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldYOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldYOSActionPerformed

    private void TxtFieldSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldSNActionPerformed

    private void ComboBoxPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxPosActionPerformed
    
    JComboBox ComboBoxPos = new JComboBox();
  
    ComboBoxPos.addItem("FacultyMemebers");
    ComboBoxPos.addItem("ResearchAsisstant");
    ComboBoxPos.addItem("Officers");
    ComboBoxPos.addItem("PartTimeEmployee");
    ComboBoxPos.addItem("Worker");
    ComboBoxPos.addItem("Chief");
    ComboBoxPos.addItem("Security");
    
    }//GEN-LAST:event_ComboBoxPosActionPerformed

    private void jButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDActionPerformed
        createPersonnel();
        if(currentPersonnel !=null){
            Personnel.personnelList.add(currentPersonnel);
            Model.setValueAt(currentPersonnel.getName(),Personnel.personnelList.size()-1, 0);
            Model.setValueAt(currentPersonnel.getSurname(),Personnel.personnelList.size()-1, 1);
            Model.setValueAt(currentPersonnel.getRegisterNumber(),Personnel.personnelList.size()-1, 2);
            Model.setValueAt(currentPersonnel.getPosition(),Personnel.personnelList.size()-1, 3);
            Model.setValueAt(currentPersonnel.getYearOfStart(),Personnel.personnelList.size()-1, 4);
        }
        this.dispose();
    }//GEN-LAST:event_jButtonADDActionPerformed

    private void jButtonCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLEARActionPerformed
        
            {   
                TxtFieldRN.setText("");
                TxtFieldSN.setText("");
                TxtFieldRN.setText("");
                TxtFieldYOS.setText("");
            }
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonCLEARActionPerformed

    private void TxtFieldNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPersonnel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxPos;
    private javax.swing.JPanel PanelAddPersonnel;
    private javax.swing.JTextField TxtFieldN;
    private javax.swing.JTextField TxtFieldRN;
    private javax.swing.JTextField TxtFieldSN;
    private javax.swing.JTextField TxtFieldYOS;
    private javax.swing.JButton jButtonADD;
    private javax.swing.JButton jButtonCLEAR;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPersonnel;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelRegNO;
    private javax.swing.JLabel jLabelSurName;
    private javax.swing.JLabel jLabelYearOfStart;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
