
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gulbe
 */
public class Monitoring extends javax.swing.JFrame {
    private Monitor currentMonitoring;
     private DefaultTableModel ModelM;
    /**
     * Creates new form Monitoring
     */
    public Monitoring() {
        initComponents();
    }
    public Monitoring(DefaultTableModel ModelM) {
        this.ModelM = ModelM;
        initComponents();
    }
    

    private void createMonitoring(){
       String RegisterNumber = TextFieldRN.getText();
       String FirstWeek = TextFieldFW.getText();
       String SecondWeek = TextFieldSW.getText();
       String ThirdWeek = TextFieldTW.getText();
       String FourthWeek = TextFieldFW.getText();
       boolean RegisterNumberCheck = RegisterNumber.isEmpty();
       boolean FirstWeekCheck = FirstWeek.isEmpty();
       boolean SecondWeekCheck = SecondWeek.isEmpty();
       boolean ThirdWeekCheck = ThirdWeek.isEmpty();
       boolean FourthWeekCheck = FourthWeek.isEmpty();
        if (RegisterNumberCheck) {
            JOptionPane.showMessageDialog(this, "Register Number Field is empty!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (FirstWeekCheck) {
            JOptionPane.showMessageDialog(this, "First Week Field is empty!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (SecondWeekCheck) {
            JOptionPane.showMessageDialog(this, "Second Week Field is empty!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (ThirdWeekCheck) {
            JOptionPane.showMessageDialog(this, "Third Week Field is empty!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
         if (FourthWeekCheck) {
            JOptionPane.showMessageDialog(this, "Fourth Week Field is empty!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        if (!RegisterNumberCheck && !FirstWeekCheck && !SecondWeekCheck && !ThirdWeekCheck && !FourthWeekCheck) {
            currentMonitoring= new Monitor(RegisterNumber , FirstWeek, SecondWeek, ThirdWeek,FourthWeek);
            JOptionPane.showMessageDialog(this, "Monitor is created Successfully!", "Sucess!", JOptionPane.INFORMATION_MESSAGE);

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        PanelMonitoring = new javax.swing.JPanel();
        LabelMon = new javax.swing.JLabel();
        LabelRN = new javax.swing.JLabel();
        LabelFW = new javax.swing.JLabel();
        LabelSW = new javax.swing.JLabel();
        LabelTW = new javax.swing.JLabel();
        LabelFORTHWEEK = new javax.swing.JLabel();
        TextFieldRN = new javax.swing.JTextField();
        TextFieldFW = new javax.swing.JTextField();
        TextFieldSW = new javax.swing.JTextField();
        TextFieldTW = new javax.swing.JTextField();
        TextFieldFOURTHWEEK = new javax.swing.JTextField();
        buttonsave = new javax.swing.JButton();
        buttonclear = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelMonitoring.setBackground(new java.awt.Color(255, 232, 245));

        LabelMon.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LabelMon.setText("MONITORING");

        LabelRN.setText("Register Number");

        LabelFW.setText("1.week");

        LabelSW.setText("2.week");

        LabelTW.setText("3.week");

        LabelFORTHWEEK.setText("4.week");

        TextFieldRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldRNActionPerformed(evt);
            }
        });

        TextFieldFW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldFWActionPerformed(evt);
            }
        });

        TextFieldTW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTWActionPerformed(evt);
            }
        });

        buttonsave.setText("ADD");
        buttonsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsaveActionPerformed(evt);
            }
        });

        buttonclear.setText("CLEAR");
        buttonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMonitoringLayout = new javax.swing.GroupLayout(PanelMonitoring);
        PanelMonitoring.setLayout(PanelMonitoringLayout);
        PanelMonitoringLayout.setHorizontalGroup(
            PanelMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMonitoringLayout.createSequentialGroup()
                .addGroup(PanelMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMonitoringLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(PanelMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelMon)
                            .addGroup(PanelMonitoringLayout.createSequentialGroup()
                                .addGroup(PanelMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelRN)
                                    .addComponent(LabelFW, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelSW, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelTW, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelFORTHWEEK, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(53, 53, 53)
                                .addGroup(PanelMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextFieldRN)
                                    .addComponent(TextFieldFW)
                                    .addComponent(TextFieldSW)
                                    .addComponent(TextFieldTW)
                                    .addComponent(TextFieldFOURTHWEEK, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))))
                    .addGroup(PanelMonitoringLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(buttonsave, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(buttonclear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        PanelMonitoringLayout.setVerticalGroup(
            PanelMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMonitoringLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LabelMon)
                .addGap(18, 18, 18)
                .addGroup(PanelMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRN)
                    .addComponent(TextFieldRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PanelMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFW)
                    .addComponent(TextFieldFW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSW)
                    .addComponent(TextFieldSW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PanelMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTW)
                    .addComponent(TextFieldTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PanelMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFORTHWEEK)
                    .addComponent(TextFieldFOURTHWEEK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMonitoringLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonclear)
                    .addComponent(buttonsave))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelMonitoring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelMonitoring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldRNActionPerformed

    private void TextFieldTWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTWActionPerformed

    private void buttonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsaveActionPerformed
         createMonitoring();
        if(currentMonitoring !=null){
            Monitor.MonitoringList.add(currentMonitoring);
            ModelM.setValueAt(currentMonitoring.getRegisterNumber(),Monitor.MonitoringList.size()-1, 0);
            ModelM.setValueAt(currentMonitoring.getFirstWeek(),Monitor.MonitoringList.size()-1, 1);
            ModelM.setValueAt(currentMonitoring.getSecondWeek(),Monitor.MonitoringList.size()-1, 2);
            ModelM.setValueAt(currentMonitoring.getThirdWeek(),Monitor.MonitoringList.size()-1, 3);
            ModelM.setValueAt(currentMonitoring.getFourthWeek(),Monitor.MonitoringList.size()-1, 4);
        }
        this.dispose();
    }//GEN-LAST:event_buttonsaveActionPerformed

    private void TextFieldFWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldFWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldFWActionPerformed

    private void buttonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonclearActionPerformed
                TextFieldRN.setText("");
                TextFieldFW.setText("");
                TextFieldSW.setText("");
                TextFieldTW.setText("");
                TextFieldFOURTHWEEK.setText("");
    }//GEN-LAST:event_buttonclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monitoring().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFORTHWEEK;
    private javax.swing.JLabel LabelFW;
    private javax.swing.JLabel LabelMon;
    private javax.swing.JLabel LabelRN;
    private javax.swing.JLabel LabelSW;
    private javax.swing.JLabel LabelTW;
    private javax.swing.JPanel PanelMonitoring;
    private javax.swing.JTextField TextFieldFOURTHWEEK;
    private javax.swing.JTextField TextFieldFW;
    private javax.swing.JTextField TextFieldRN;
    private javax.swing.JTextField TextFieldSW;
    private javax.swing.JTextField TextFieldTW;
    private javax.swing.JButton buttonclear;
    private javax.swing.JButton buttonsave;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
